pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
    }

    stages {
        stage('Set AWS Credentials') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'JenkinsTest'
                ]]) {
                    sh '''
                    export AWS_DEFAULT_REGION=$AWS_REGION
                    aws sts get-caller-identity
                    '''
                }
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/DennistonShaw/Class7-HW-Deliverables.git'
            }
        }

        stage('Initialize Terraform') {
            steps {
                dir('week27-hw-jenkins') {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'JenkinsTest'
                    ]]) {
                        sh '''
                        export AWS_DEFAULT_REGION=$AWS_REGION
                        terraform init
                        '''
                    }
                }
            }
        }

        stage('Plan Terraform') {
            steps {
                dir('week27-hw-jenkins') {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'JenkinsTest'
                    ]]) {
                        sh '''
                        export AWS_DEFAULT_REGION=$AWS_REGION
                        terraform plan -out=tfplan
                        '''
                    }
                }
            }
        }

        stage('Apply Terraform') {
            steps {
                input message: "Approve Terraform Apply?", ok: "Deploy"
                dir('week27-hw-jenkins') {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'JenkinsTest'
                    ]]) {
                        sh '''
                        export AWS_DEFAULT_REGION=$AWS_REGION
                        terraform apply -auto-approve tfplan
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Terraform deployment completed successfully!'
        }
        failure {
            echo 'Terraform deployment failed!'
        }
    }
}